### ISSUE TITLE
How to mount USB serial device e.g. ttyACM0

### ISSUE THREAD

**Issue by JosefStepanik** [WAGO/pfc-firmware-sdk#12]
Hi, 
how i can mount to this Linux distribution a USB serial device? I need to control in my application this butterfly valve 
https://www.idealvac.com/files/manuals/Ideal_Vacuum_CommandValve_Users_Manual_Rev_CV003A.pdf ?
I see this in Ubuntu like ttyACM0 device. Which approach is the right? A see this device in WagoTP via command "lsusb" or udevadm info. But i can not make any handle.
JS

**Comment by Helmut-Saal** [comment]
Hi, please contact Wago Support to get help.
Github is not usefull as a support platform.
Wago Support Minden: 057188744555
