### ISSUE TITLE
Kernel header md5sum

### ISSUE THREAD

**Issue by oaox** [WAGO/pfc-firmware-sdk#13]
A fresh Ubuntu 16.04.5 install under Virtual box running under Kubuntu 
ptxdist go -q stops here:

started : kernel-header.get
ptxdist: error: Wrong md5sum for 'kernel-header' (/home/oao/wago/ptxproj/src/linux-4.9.146.tar.xz)
make: *** [/home/oao/wago/ptxproj/platform-wago-pfcXXX/state/kernel-header.get] Error 1

Linux oao-VirtualBox 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by Thomas-Brandt** [comment]
It seams that you didn't follow the guide (README.md)
Please check your GIT-LFS installation and also please check that the
linux-4.9.146.tar.xz is checked out via the LFS.
