### ISSUE TITLE
Adding psycopg2 to Python3 package

### ISSUE THREAD

**Issue by TiagoLaraTecSys** [WAGO/pfc-firmware-sdk#14]
Hello! I'm from Brazil, this is a very nicely document about create package .ipk to the PFC family! Thank you very much.

Do you know how its possible to add the module psycopg2 to the package python3 of the project builded?

I want to use a PFC8207 to connect to a PostGreSQL database to retrieve informations on the webvisu, so i think to use SysCommandLine2 Function on the e!cockpit to use a .py script that connect to the database, its possible?? Thnx!

**Comment by Thomas-Brandt** [comment]
Hello,
I think the best idea is to adapt from a existing python3 package. 
E.g. take a look at /usr/local/lib/ptxdist-2017.11.1/rules/python3-tornado.make /usr/local/lib/ptxdist-2017.11.1/rules/python3-tornado.in.
Copy those to your <ptxdist>/rules directory. Rename those to python3-pycopg2.[make/in]. 
Change the parameter and names of that rule file.
After successfully created the rule files you'll have the module automatically installed in your image.
