### ISSUE TITLE
WAGO-PFC-SDK  installation instruction. wrong paths at "4) Configure project environment" 

### ISSUE THREAD

**Issue by dicomataal** [WAGO/pfc-firmware-sdk#17]
Paths at steps are wrong, it is require to prepend "pfc-firmware-sdk" path to "configs/wago-pfcXXX/..."

in 4.1 should be:   _ptxdist select pfc-firmware-sdk/configs/wago-pfcXXX/ptxconfig_generic_
in 4.2 should be:   _ptxdist select pfc-firmware-sdk/configs/wago-pfcXXX/platformconfig_

**Comment by Thomas-Brandt** [comment]
If you consider 3.2 the path is correct.
