### ISSUE TITLE
libbpf.so.0 undefined refernce to..

### ISSUE THREAD

**Issue by umbaman** [WAGO/pfc-firmware-sdk#21]
Several undefined referencies

```
arm-linux-gnueabihf-gcc -std=gnu99 -O0 -g3  -Wall -Wstrict-prototypes -fno-strict-aliasing -D_REENTRANT  -I/home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/include  $(/home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-cross/bin/arm-linux-gnueabihf-pkg-config --cflags glib-2.0 || echo "pkg-config-failed") -o profinetdemo_idevice profinetdemo_idevice.o -lprofinet  -DLINUX -lpthread -lboost_system -lboost_thread -lrt -L/home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/lib -L/home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib  $(/home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-cross/bin/arm-linux-gnueabihf-pkg-config --libs glib-2.0 || echo "pkg-config-failed") 

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_strptr'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_end'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_memory'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_ndxscn'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `gelf_getrel'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_rawdata'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `gelf_getsym'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `gelf_getclass'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_getdata'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_getscn'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_begin'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `gelf_getshdr'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_nextscn'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_version'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_errmsg'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_getshdrstrndx'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `gelf_getehdr'

collect2: error: ld returned 1 exit status

make[1]: Leaving directory '/home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/build-target/profinetdemo/idevice'

make[1]: *** [Makefile:96: all] Error 1
```

**Comment by Thomas-Brandt** [comment]
Hi,
I was facing the same problem yesterday. 
Please find my commit (Hotfix) https://github.com/WAGO/pfc-firmware-sdk/commit/19d06251067ff91428adae6e1d35c181c74e9dc0

This will solve the Problem

**Comment by umbaman** [comment]
Hello This is my output still
` make[1]: Entering directory '/home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/build-target/profinetdemo/idevice'

/home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target

arm-linux-gnueabihf-gcc -std=gnu99 -O0 -g3  -Wall -Wstrict-prototypes -fno-strict-aliasing -D_REENTRANT  -I/home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/include  $(/home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-cross/bin/arm-linux-gnueabihf-pkg-config --cflags glib-2.0 || echo "pkg-config-failed") -o profinetdemo_idevice profinetdemo_idevice.o -lprofinet  -DLINUX -lpthread -lboost_system -lboost_thread -lrt -L/home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/lib -L/home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib  $(/home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-cross/bin/arm-linux-gnueabihf-pkg-config --libs glib-2.0 || echo "pkg-config-failed") 

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_strptr'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_end'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_memory'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_ndxscn'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `gelf_getrel'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_rawdata'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `gelf_getsym'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `gelf_getclass'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_getdata'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_getscn'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_begin'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `gelf_getshdr'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_nextscn'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_version'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_errmsg'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `elf_getshdrstrndx'

/opt/gcc-Toolchain-2019.12/arm-linux-gnueabihf/bin/../lib/gcc/arm-linux-gnueabihf/9.2.1/../../../../arm-linux-gnueabihf/bin/ld: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/sysroot-target/usr/lib/libbpf.so.0: undefined reference to `gelf_getehdr'

collect2: error: ld returned 1 exit status

make[1]: Leaving directory '/home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/build-target/profinetdemo/idevice'

make[1]: *** [Makefile:96: all] Error 1

make: *** [/usr/local/lib/ptxdist-2017.11.1/rules/post/ptxd_make_world_compile.make:22: /home/ilias/Development/Wago/ptxproj/platform-wago-pfcXXX/state/profinetdemo.compile] Error 2 `

and this is my _src/profinetdemo/idevice/Makefile_ contents after your comment
`#LDFLAGS += -lprofinet 

LDFLAGS += -lelf -lprofinet

LDFLAGS += -DLINUX -lpthread -lboost_system -lboost_thread -lrt

`

**Comment by umbaman** [comment]
ok, fixed.
I had to edit 
platform-wago-pfcXXX/build-target/profinetdemo/idevice/Makefile
after all
> Hello I still have the same issue
> 
> This is my src/profinetdemo/idevice/Makefile contents after your comment
> 
> ```
> 
> LDFLAGS += -lelf -lprofinet
> 
> LDFLAGS += -DLINUX -lpthread -lboost_system -lboost_thread -lrt
> ```

**Comment by Thomas-Brandt** [comment]
I think you've not cleaned the stage! 
Perform a `ptxdist clean profinetdemo` to clear the stage an do a fresh checkout/compile of that stage.

**Comment by umbaman** [comment]
Correct! I did that and after that it worked. Unfortunately I am not familiar on ptxdist so what I did, is that I just deleted all .o files from the directory.
Thanks a lot!

> I think you've not cleaned the stage! Perform a `ptxdist clean profinetdemo` to clear the stage an do a fresh checkout/compile of that stage.
