### ISSUE TITLE
Proposal to update OpenVPN dependency to 2.5.x

### ISSUE THREAD

**Issue by kohlerdominik** [WAGO/pfc-firmware-sdk#23]
OpenVPN 2.4, which is currently installed by default, faces it's End Of Life by end of May 2022, so roughly in 3 Months. This means it will enter "old stable support", which will receive security bugfixes for at least 12 more months.

Currently installed is OpenVPN 2.4.6, which was released in April 2018. Therefore, I think it's overdue to update this crititcal security component.

I propose to update the OpenVPN dependency with the next firmware release to 2.5.x. As far as I'm aware, OVPN 2.5.x should be fully compatible with config files vom 2.4.x, so therefore there should be no bigger issues with backwards compatiblity. However, users are still free to stick with an older firmware if OpenVPN 2.4 is required.

There are the directives `no-iv`, `client-vert-not-required`, `ifconfig-pool-linear` and `key-method 1` were deprectated features in 2.4.x and were removed now. It means, this directives did throw DEPRECATED-warnings for more than 5 years now.

See full list of removed features in [2.5:Deprecated Features](https://github.com/OpenVPN/openvpn/blob/release/2.5/Changes.rst)

**Comment by Thomas-Brandt** [comment]
With FW22-V03.10.8 we have updated OpenVPN to version 2.5.5
