### ISSUE TITLE
How to make sd.hdimg create an extra partition for pre-loaded data using the full SD size?

### ISSUE THREAD

**Issue by TruDan** [WAGO/pfc-firmware-sdk#24]
Hi, i've been trying to copy the configurations for `image-sd` / `sd.hdimg` etc to create a 3rd partition with some files we would like to be pre-installed. my custom tgz is built fine, but when generating the image i keep getting issues such as:

```  
ERROR: hdimage(herosd.hdimg): partitions exceed device size
```

Even if i set the image.size to something ridiculously big like 16G.

I'm trying to get an image file that we can flash to the SD card that has the following partition layout

```
0M         ?M               240M          32G(SD-Card size)
| boot     | root           | hero ...... |
```

the base firmware is copied to the internal flash upon first boot, then should be set to boot from the internal flash instead of sd (this also doesnt work properly but that's another story/issue, fix currently is after copying the files to just fully delete the boot partition from the SD card)

upon boot i can then mount the 3rd "hero" partition to `/hero` and use this within the linux environment.

------

Could you please provide some examples/point me in the right direction as to how to configure an extra partition on the SD card (which is not part of the "firmware" per say / not copied to internal flash) which can be automatically mounted like this? 

I've been stuck on this issue for over a week now, it's the final step left for our custom firmware build which would save us 2-3+ hours of setup per PLC, of which we have ~500 to set up, so its really beneficial to have these things in the img so our setup just becomes "write img to SD card, insert SD card to PLC + power on PLC, wait until USR LED turns green and its ready to use further!"

For the configs i customised, please see my gist [here](https://gist.github.com/TruDan/5969865561e6c32b4ed51605e3c58b37)

Any help with this will be really greatly appreciated!! Thanks!
Dan

**Comment by Thomas-Brandt** [comment]
Hello Dan,

I think the problem is that you try to "attach" a tar-gz as partition.
You need your Image-File (hero.ext2) in the [config~images~herosd.config](https://gist.github.com/TruDan/5969865561e6c32b4ed51605e3c58b37#file-config-images-herosd-config)
