### ISSUE TITLE
codesys 3.5

### ISSUE THREAD

**Issue by tomas1515** [WAGO/pfc-firmware-sdk#25]
Can you tell me how the SDK is related to working in the Codesys 3.5 or eCockpit environment?

**Comment by falk-werner** [comment]
I assume that your request is about the transition from e!Cockpit to pure CODESYS, am I right?

PFC firmware images up to and including firmware 22 (03.10.xx) support e!Cockpit.
PFC firmware images starting with firmware 23 (04.01.xx) and higher do not support e!Cockpit anymore but pure CODESYS.

If you are interested in firmware 23 (04.01.xx), have a look at [pfc-firmware-sdk-G2](https://github.com/WAGO/pfc-firmware-sdk-G2).

**Comment by tomas1515** [comment]
Yes, you said everything correctly. Firmware 23 is already out? Can not understand...

**Comment by falk-werner** [comment]
Firmware 23 was released in November 2022 for PFC200 G2 and CC100 devices. 

Please note, that PFC200 G1 devices are discontinued and replaced by PFC200 G2 devices. They will receive security and package updates. Therefore, firmware 22 is maintained as a long term support (LTS) firmware.

Please refer to [pfc-firmware-sdk-G2](https://github.com/WAGO/pfc-firmware-sdk-G2) for new firmware releases.
