### ISSUE TITLE
ptxdist installs to /usr/local/lib/ptxdist-????.??.?

### ISSUE THREAD

**Issue by falk-werner** [WAGO/pfc-firmware-sdk#4]
**Background**

I observed some strange behavior after installing ptxdist as documented in chapter 3 of README.md: ptxdist installs to /usr/local/lib/ptxdist-????.??.? instead of /usr/local/lib/ptxdist-2017.11.1.

**Problem**

Since the used ptxdist version is mentioned in a configuration file (configs/wago-pfcXXX/ptxconfig_generic), I got some issues compiling the firmware.

**Investigation**

The correct version is set during ptxdist installation by [setlocalversion](https://github.com/WAGO/ptxdist/blob/master/scripts/kernel/setlocalversion) script. It uses some heuristics to determine the correct version (including git and svn probes).

Since compile step (ptxdist go) seems to require a fixed version (2017.11.1), I solved the issue locally by creating a file .tarball-version:

    echo "2017.11.1" > ~/ptxdist/.tarball-version

But I am not sure, if this "solution" is sufficient.

**Comment by Thomas-Brandt** [comment]
It seams that the file .tarball-version was missing in the repo.
I´ve added it and now it works like a charm!
Check https://github.com/WAGO/ptxdist/commit/8d495aab3689d2bff0ca82f2850de8e2bc812aeb
