### ISSUE TITLE
Version numbering seems to be off

### ISSUE THREAD

**Issue by Jabbl** [WAGO/pfc-firmware-sdk#7]
While previous versions of the PFC200 firmware seems to follow an incremental version numbering in parenthesis after Firmware Revision, the current version seems to have jumped quite a bit.

Previous firmware says (11) while the self-compiled firmware says (99)
Is this intended, is it a bug, or am I simply doing something wrong?

Firmware 11:
![FW11](https://user-images.githubusercontent.com/23106475/58947194-b942ac80-8787-11e9-983b-fed089d60e6e.PNG)

Current firmware:
![FW12](https://user-images.githubusercontent.com/23106475/58947209-c3fd4180-8787-11e9-82f5-3e258e39027e.PNG)

**Comment by Thomas-Brandt** [comment]
Hi this is correct..because of that the official version is marked as major.minor.relase (internal index).
So you dont have to worry about the (99) its just a internal index.

**Comment by Ekristoffe** [comment]
If I may the (internal index) will be 99 for beta FW or self made FW. only wago released FW will have an index different from 99 (which is a mean to know if the FW is an official or not)
