### ISSUE TITLE
 Linaro tool  error

### ISSUE THREAD

**Issue by undulators** [WAGO/pfc-firmware-sdk#8]
There is a problem with the compiler your provided。
The questions are as follows:
arm-linux-gnueabihf-gcc: error trying to exec '/opt/LINARO.Toolchain-2017.10/arm-linux-gnueabihf/bin/../libexec/gcc/arm-linux-gnueabihf/5.5.0/cc1': execv: Exec format error
arm-linux-gnueabihf-gcc: error trying to exec '/opt/LINARO.Toolchain-2017.10/arm-linux-gnueabihf/bin/../libexec/gcc/arm-linux-gnueabihf/5.5.0/cc1': execv: Exec format error

**Comment by Thomas-Brandt** [comment]
Hi,
thanks for coming back!
Are you using a 64bit operating system as advised?
Please check with $uname -a.

**Comment by undulators** [comment]
Hi,
this is my system information:
Linux undulators 4.15.0-29-generic #31~16.04.1-Ubuntu SMP Wed Jul 18 08:54:04 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by undulators** [comment]
Hi,
   Thank you for your reply!
   I went back to Linaro's official website to download the 5.5 version of the compiler.Here is my download link:
  https://releases.linaro.org/components/toolchain/binaries/5.5-2017.10/arm-linux-gnueabihf/
  The file name of the specific download is as follows:
  gcc-linaro-5.5.0-2017.10-i686_arm-linux-gnueabihf.tar.xz
  it can compile successfully.but I am not sure if there are any problems.
